version: "3.3"
services:
  mongodb:
    image: mongo:3.4
    restart: always
    volumes:
    - type: bind
      source: /opt/mongo # 数据库文件存放地址，根据需要修改为本地地址
      target: /data/db
  redis:
    image: redis:4.0.6
    restart: always
    command: redis-server --appendonly yes
    volumes:
    - type: bind
      source: /opt/redis # redis 数据文件存放地址，根据需要修改为本地地址
      target: /data
  web:
    image: easymock/easymock:1.6.0
    restart: always
    command: /bin/bash -c "npm start"
    links:
    - mongodb:mongodb
    ports:
    - 7300:7300
    volumes:
    - type: bind
      source: /opt/web/production.json # 配置地址，请使用本地配置地址替换
      target: /home/easy-mock/easy-mock/config/production.json
