version: "3.3"

services:
  mongodb:
    image: mongo:3.4
    restart: always
    volumes:
      - mongo_data: /data/db

  redis:
    image: redis:4.0.6
    restart: always
    command: redis-server --appendonly yes
    volumes:
    - redis_data: /data

  web:
    image: easymock/easymock:1.6.0
    restart: always
    command: /bin/bash -c "npm start"
    links:
    - mongodb:mongodb
    ports:
    - 7300:7300
    volumes:
    - web_data/production.json: /home/easy-mock/easy-mock/config/production.json

  volumes:
    mongo_data:
    redis_data:
    web_data:
